### ISSUE TITLE
违反了Eula协议哦~

### ISSUE THREAD

**Issue by cluom** [a1393323447/aseprite-builder#1]
https://github.com/aseprite/aseprite/blob/main/EULA.txt

**Comment by a1393323447** [comment]
大概是哪一条呢？我看了协议，好像是只要不分发编译好的二进制文件就没有问题。

**Comment by cluom** [comment]
我在tag里面可以下载你编译好的文件 所以相当于你在分发了

**Comment by a1393323447** [comment]
编译好的文件，我应该很久之前就删掉了。你检查一下。
