### ISSUE TITLE
Windows: libcrypto-1_1-x64.dll not found

### ISSUE THREAD

**Issue by doglikemakinggame** [a1393323447/aseprite-builder#18]
由于找不到 libcrypto-1_1-x64.dll ，无法继续执行代码 。  即使下载了这个文件 ，运行时还是会提示 程序运行错误 00100 。。。
这是啥情况？

**Comment by doglikemakinggame** [comment]
steam上下的 1.3.6 是可以运行的

**Comment by a1393323447** [comment]
下载文件 [openssl-1.1.1w.zip](https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-1.1.1w.zip) 。将 `x64/bin/libcrypto-1_1-x64.dll` 放到和 `aseprite.exe` 同一个目录下，应该就可以正常运行了。我可能之后再找个时间看看编译流程。

**Comment by doglikemakinggame** [comment]
卧槽。我自己下的不行，用你这个是可以的。解决了。
